name: Python Workflow

on:
  workflow_dispatch:
    inputs:
      phone_number:
        description: "Số điện thoại để chạy tool"
        required: true
        default: "0123456789"
      spam_count:
        description: "Số lần spam"
        required: true
        default: "10"
  schedule:
    - cron: '0 6-18 * * *' # Chạy từ 6h sáng đến 6h tối hàng ngày

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r re.txt

    - name: Run tool.py and input data
      run: |
        echo -e "${{ inputs.phone_number }}\n${{ inputs.spam_count }}" | python tool.py
