name: Python Workflow

on:
  workflow_dispatch:
    inputs:
      phone_number:
        description: "Số điện thoại để chạy tool"
        required: false # Không bắt buộc khi chạy thủ công
      spam_count:
        description: "Số lần spam"
        required: false # Không bắt buộc khi chạy thủ công
  schedule:
   - cron: '0 */23-11 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      PHONE_NUMBER: '0' # Giá trị mặc định cho số điện thoại
      SPAM_COUNT: '0' # Giá trị mặc định cho số lần spam

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r re.txt

    - name: Run tool.py and input data
      run: |
        # Kiểm tra xem có input từ người dùng không
        if [ -z "${{ inputs.phone_number }}" ]; then
          PHONE_NUMBER="${{ env.PHONE_NUMBER }}"
        else
          PHONE_NUMBER="${{ inputs.phone_number }}"
        fi

        if [ -z "${{ inputs.spam_count }}" ]; then
          SPAM_COUNT="${{ env.SPAM_COUNT }}"
        else
          SPAM_COUNT="${{ inputs.spam_count }}"
        fi

        echo -e "$PHONE_NUMBER\n$SPAM_COUNT" | python tool.py
