name: Auto

on:
  workflow_dispatch:
    inputs:
      phone_number:
        description: "Số điện thoại để chạy tool"
        required: false
      spam_count:
        description: "Số lần spam"
        required: false
      threads:
        description: "Số luồng chạy song song"
        required: false
        default: "3" # Giá trị mặc định khi chạy thủ công
  schedule:
    - cron: '*/5 23 * * *'
    - cron: '*/5 0-11 * * *'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Determine number of threads
        run: |
          if [ -z "${{ inputs.threads }}" ]; then
            THREADS="3" # Giá trị mặc định khi chạy tự động
          else
            THREADS="${{ inputs.threads }}"
          fi

          # Tạo ma trận động dựa trên số luồng
          THREAD_LIST=$(seq 1 $THREADS)
          echo "::set-output name=matrix::{\"thread\": [$THREAD_LIST]}"
      - id: set-matrix
        run: |
          echo '${{ steps.determine-number-of-threads.outputs.matrix }}' > matrix.json
          echo "::set-output name=matrix::${{ steps.determine-number-of-threads.outputs.matrix }}"
      - name: Upload matrix as artifact
        uses: actions/upload-artifact@v3
        with:
          name: matrix
          path: matrix.json
          retention-days: 1

  run-python:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    env:
      PHONE_NUMBER: '0123456789' 
      SPAM_COUNT: '10' 
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r re.txt
      - name: Download matrix artifact
        uses: actions/download-artifact@v3
        with:
          name: matrix
      - name: Run tool.py and input data # Đã thêm run key vào đây
        run: |
          if [ -z "${{ inputs.phone_number }}" ]; then
            PHONE_NUMBER="${{ env.PHONE_NUMBER }}"
          else
            PHONE_NUMBER="${{ inputs.phone_number }}"
          fi

          if [ -z "${{ inputs.spam_count }}" ]; then
            SPAM_COUNT="${{ env.SPAM_COUNT }}"
          else
            SPAM_COUNT="${{ inputs.spam_count }}"
          fi

          timeout 1m echo -e "$PHONE_NUMBER\n$SPAM_COUNT" | python tool.py
