name: Python Workflow

on:
  # Sự kiện khi push code lên nhánh main
  push:
    branches:
      - main
  # Sự kiện khi mở pull request
  pull_request:
    branches:
      - main
  # Sự kiện chạy thủ công
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Thay bằng version Python bạn cần

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r re.txt

    # Step 4: Run the script
    - name: Run tool.py
      run: python tool.py
