name: Python Workflow

on:
  workflow_dispatch:
    inputs:
      phone_number:
        description: "Số điện thoại để chạy tool"
        required: true
        default: "0123456789"
      spam_count:
        description: "Số lần spam"
        required: true 
        default: "10"
  schedule:
    # Chạy mỗi giờ từ 6h sáng đến 6h tối (UTC+7)
    - cron: '0 23-11 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check time
      run: |
        hour=$(TZ='Asia/Ho_Chi_Minh' date +%H)
        if [ $hour -lt 6 ] || [ $hour -ge 18 ]; then
          echo "Outside working hours (6:00-18:00)"
          exit 0
        fi

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python  
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r re.txt

    - name: Run tool.py and input data
      env:
        DEFAULT_PHONE: "0123456789"  # Điền số điện thoại mặc định của bạn
        DEFAULT_COUNT: "10"          # Điền số lần spam mặc định
      run: |
        PHONE="${{ github.event.inputs.phone_number || env.DEFAULT_PHONE }}"
        COUNT="${{ github.event.inputs.spam_count || env.DEFAULT_COUNT }}"
        echo -e "$PHONE\n$COUNT" | python tool.py
